# Generated by Django 5.1.5 on 2025-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
