# Generated by Django 5.1.5 on 2025-06-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_users', '0002_storeuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='code_word',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='кодовое слово'),
        ),
    ]
