# Generated by Django 5.1.5 on 2025-05-14 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('requires_delivery', models.BooleanField(default=False, verbose_name='Требуется доставка')),
                ('delivery_adress', models.CharField(max_length=50, verbose_name='адрес доставки')),
                ('payment_type', models.BooleanField(default=False, verbose_name='способ оплаты')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Создан'), (1, 'Оплачен'), (2, 'Отменен'), (3, 'В пути'), (4, 'Доставлен')], default=0, verbose_name='Статус заказа')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'user_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество товара')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.userorders')),
            ],
            options={
                'verbose_name': 'Проданный товар',
                'verbose_name_plural': 'Проданные товары',
                'db_table': 'orderitem',
            },
        ),
    ]
