# Generated by Django 5.1.5 on 2025-05-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorders',
            name='delivery_adress',
            field=models.CharField(max_length=70, verbose_name='адрес доставки'),
        ),
    ]
